api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
        mime_types: ['multipart/form-data']
    swagger:
        versions: [3] 
    collection:
        pagination:
            items_per_page: 3
    